<?php
namespace GoetasWebservices\WsdlToPhp\Generation;

use Exception;
use GoetasWebservices\XML\SOAPReader\Soap\Operation;
use GoetasWebservices\XML\SOAPReader\Soap\OperationMessage;
use GoetasWebservices\XML\SOAPReader\Soap\Service;
use GoetasWebservices\XML\WSDLReader\Wsdl\Message\Part;
use GoetasWebservices\Xsd\XsdToPhp\Jms\YamlConverter;

/**
 * Builds Symfony Validator YAML metadata for the SOAP envelope/header/body-part
 * wrapper classes generated by {@see PhpSoapConverter} / {@see JmsSoapConverter}.
 *
 * Field-level rules (NotNull, Length, Choice, ...) for the actual message content
 * come from the underlying {@see YamlConverter}/{@see \GoetasWebservices\Xsd\XsdToPhp\Jms\YamlValidatorConverter}
 * walking the WSDL-embedded schema directly (via visitElementDef()/visitType()) - this
 * class only adds the "cascade into it" (Valid) and "the part is always present when
 * the message occurs" (NotNull on body parts) rules for the thin wrapper classes it
 * itself generates. A SOAP header is, by convention, optional, so no NotNull is added
 * to it.
 */
class ValidatorSoapConverter extends SoapConverter
{
    private $classes = [];

    private $converter;

    public function __construct(YamlConverter $converter, array $baseNs = array())
    {
        $this->converter = $converter;
        parent::__construct($baseNs);
    }

    public function visitServices(array $services)
    {
        $visited = array();
        $this->classes = array();
        foreach ($services as $service) {
            $this->visitService($service, $visited);
        }
        return $this->getTypes();
    }

    /**
     * @return array
     */
    public function getTypes()
    {
        uasort($this->classes, function ($a, $b) {
            return strcmp(key($a), key($b));
        });

        $ret = array();

        foreach ($this->classes as $definition) {
            $classname = key($definition);
            if (strpos($classname, '\\') !== false) {
                $ret[$classname] = $definition;
            }
        }

        return $ret;
    }

    private function visitService(Service $service, array &$visited)
    {
        if (isset($visited[spl_object_hash($service)])) {
            return;
        }
        $visited[spl_object_hash($service)] = true;

        foreach ($service->getOperations() as $operation) {
            $this->visitOperation($operation, $service);
        }
    }

    private function visitOperation(Operation $operation, Service $service)
    {
        $this->visitMessage($operation->getInput(), 'input', $operation, $service);
        if (null !== ($output = $operation->getOutput())) {
            $this->visitMessage($output, 'output', $operation, $service);
        }
    }

    private function visitMessage(OperationMessage $message, $hint, Operation $operation, Service $service)
    {
        if (!isset($this->classes[spl_object_hash($message)])) {
            $className = $this->findPHPName($message, $this->inflector->classify($hint), $this->baseNs[$service->getVersion()]['parts']);
            $data = array();
            $class = array();
            $class[$className] = &$data;

            $this->visitMessageParts($data, $message->getBody()->getParts());

            $this->classes[spl_object_hash($message)] = &$class;

            $messageClassName = $this->findPHPName($message, $this->inflector->classify($hint), $this->baseNs[$service->getVersion()]['messages']);
            $envelopeClass = array();
            $envelopeData = array();
            $envelopeClass[$messageClassName] = &$envelopeData;

            // The body is structurally required whenever the message occurs; the
            // parts wrapper's own properties already carry their schema-derived
            // rules, "Valid" just cascades into it.
            $bodyRules = [];
            if ($message->getBody()->getParts()) {
                $bodyRules[] = ['NotNull' => null];
                $bodyRules[] = ['Valid' => null];
            }
            $envelopeData['properties']['body'] = $bodyRules;

            // A SOAP header is optional by convention: cascade validation into it
            // when present, but never require it.
            $envelopeData['properties']['header'] = [
                ['Valid' => null],
            ];

            $this->classes[] = &$envelopeClass;

            $headersClass = array();
            $headersData = array();

            $className = $this->findPHPName($message, $this->inflector->classify($hint), $this->baseNs[$service->getVersion()]['headers']);

            $headersClass[$className] = &$headersData;
            $this->classes[] = &$headersClass;

            foreach ($message->getHeaders() as $header) {
                $this->visitMessageParts($headersData, [$header->getPart()]);
            }
        }
        return $this->classes[spl_object_hash($message)];
    }

    private function visitMessageParts(&$data, array $parts)
    {
        /**
         * @var $part Part
         */
        foreach ($parts as $part) {
            if ($part->getElement()) {
                $name = $part->getElement()->getName();
                $this->converter->visitElementDef($part->getElement()->getSchema(), $part->getElement());
            } else {
                $name = $part->getName();
                $this->converter->visitType($part->getType());
            }

            // Each declared part is structurally required whenever the message
            // occurs; "Valid" cascades into its own schema-derived rules.
            $data['properties'][$this->inflector->camelize($name)] = [
                ['NotNull' => null],
                ['Valid' => null],
            ];
        }
    }

    private function findPHPName(OperationMessage $message, $hint = '', $nsadd = '')
    {
        $name = $this->inflector->classify($message->getMessage()->getOperation()->getName()) . $hint;
        $targetNs = $message->getMessage()->getDefinition()->getTargetNamespace();

        $namespaces = $this->converter->getNamespaces();

        if (!isset($namespaces[$targetNs])) {
            throw new Exception(sprintf("Can't find a PHP namespace to '%s' namespace", $targetNs));
        }
        $ns = $namespaces[$targetNs];
        return $ns . $nsadd . "\\" . $name;
    }
}
