name: Tests

on:
  push:
    branches: [master]
  pull_request:

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['7.4', '8.0', '8.1', '8.2', '8.3', '8.4']
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
      - run: composer update --no-interaction --no-progress
      - run: vendor/bin/phpunit

  phpunit-lowest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none
      - run: composer update --no-interaction --no-progress --prefer-lowest --prefer-stable
      - run: vendor/bin/phpunit
